### ISSUE TITLE
Diablo II Launcher on Linux(Ubuntu 16.04) 

### ISSUE THREAD

**Issue by warriv95** [GreenDude120/PoD-Launcher#13]
### Hello Greendude120!
I would like to start by commending you and the team for the great work on Diablo II - lod to start a private server for Path of Diablo.  Because I am an old Diablo fan and have been growing up playing it I'm eternally grateful for getting Diablo II back into the world with a healthy community!

However!! I'm running the game on Linux with Ubuntu 16.04 gnome 3, and the launcher does not start in wine 1.6.2. I have played around with Firejail(Sandboxie equivalent to Linux system) with no results. If I reboot into Windows 7 it runs without problems and I can update via the launcher, so nothing is impossible. But If it's possible to upload the "Patch_d2.mpq" to a server that is the equivalent to the launcher  or a link. 
I understand that the launcher might update the Diablo II root files and the download would be bothersome. If the application of the update consists of copy - paste the .rar files into Diablo II root then maybe the download link would work. 

Best regards 
Warriv95

PS: Have a nice Picture http://imgur.com/znZXwb7 & http://imgur.com/TyvXJCh DS

**Comment by GreenDude120** [comment]
we dont support linux and dont know anything about but bere is the link: https://github.com/GreenDude120/PoD-Launcher/releases/tag/1

**Comment by Dav92** [comment]
It should work with Wine. But IIRC you need to manually install .NET-Framework 4.5 or 4.6. You can search the PoD reddit for posts about it (at least one person got it working).

**Comment by tslnox** [comment]
Thanks for the file. Does the launcher do anything else besides downloading the appropriate files? I see it downloads a bunch of dlls, do I have to load them (with PlugY) to play singleplayer properly?

**Comment by GreenDude120** [comment]
It does a bunch of stuff and is mandatory to run. Plugy is not supported officially and nor is singleplayer.

**Comment by tslnox** [comment]
Alright, thanks.
