### ISSUE TITLE
Launcher crashes when settings file is broken

### ISSUE THREAD

**Issue by Fridcot** [GreenDude120/PoD-Launcher#23]
Hi,

For some reason I couldn't manage to start the launcher. After some debugging I've noticed that the settings couldn't be loaded. 

The launcher should ignore broken file and create a new one or at least show what the problem is.

[An example of a broken settings file](https://github.com/GreenDude120/PoD-Launcher/files/4772617/user.config.log)

**Comment by GreenDude120** [comment]
resolved
