### ISSUE TITLE
Cannot find parent files on Wine

### ISSUE THREAD

**Issue by aliankarali** [GreenDude120/PoD-Launcher#29]
I am using wine on macos. First time I install the launcher and launch it as the last step of the installation process, everything works fine and files are downloaded and I can play the game. Next time I open the Path of Diablo Launcher.exe, it shows an error in the event log something like parent game files are not found and the button is grey and reads Failed.

Any idea where I might look for troubleshooting? Where is this config saved? How does the launcher make this check?

**Comment by GreenDude120** [comment]
Sorry we don't officially support Mac. I'd recommend installing via this unofficial guide which works well for macs. https://pathofdiablo.com/wiki/index.php?title=Mac

**Comment by aliankarali** [comment]
Well I had done same as the guide, but I will try to contact that person on Discord noted at the end of the guide. Thanks.

**Comment by abienz** [comment]
Did you find a solution, I'm having a similar issue but on Linux

**Comment by aliankarali** [comment]
Make sure you run the wine command in the same as directory as the executable. So cd first. That might have solved the issue for me. If that doesn't do, there is a wine friendly port of the launcher here: https://github.com/pohmelie/pypod-launcherdo
