### ISSUE TITLE
Non-existent url in files.xml

### ISSUE THREAD

**Issue by pohmelie** [GreenDude120/PoD-Launcher#32]
Hi, I'm the author of [pypod-launcher](https://github.com/pohmelie/pypod-launcher). My launcher reject update if something went wrong, but I did not watch logs until today. I saw that url https://pathofdiablo.com/2xbr-hybrid-v5-gamma.glsl do not exist and corrupts update. https://github.com/GreenDude120/PoD-Launcher/blame/master/files.xml#L165

**Comment by GreenDude120** [comment]
Thanks this should be fixed now please try again.

**Comment by pohmelie** [comment]
File is ok now. Thank you.
